ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  type: Prefix
  path: /grafana/?(.*)
  hosts:
    - cluster.minikube.internal

grafana.ini:
  server:
    domain: cluster.minikube.internal
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true

persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 5Gi

sidecar: 
  datasources:
    enabled: true

datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki.loki-stack.svc.cluster.local:3100
      access: proxy
