kind: Namespace 
apiVersion: v1 
metadata: 
  name: volume-experiment
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
  namespace: volume-experiment
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 10k
---
kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: webapp
  namespace: volume-experiment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: webapp
  template: 
    metadata: 
      labels: 
        app: webapp
    spec: 
      containers: 
        - name: nginx 
          image: nginx:latest 
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.5"
              memory: "50Mi"
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html 
      volumes: 
      - name: data
        persistentVolumeClaim: 
          claimName: database-pvc      
---
kind: Service
apiVersion: v1 
metadata: 
  name: webapp-svc
  namespace: volume-experiment
spec: 
  type: NodePort
  ports: 
    - port: 80 
  selector: 
    app: webapp
