kind: Namespace 
apiVersion: v1 
metadata: 
  name: volume-experiment
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
  namespace: volume-experiment
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 10k
---
kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: webapp
  namespace: volume-experiment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: webapp
  template: 
    metadata: 
      labels: 
        app: webapp
    spec: 
      containers: 
        - name: app 
          image: nginx:latest 
          resources:
            limits:
              cpu: "1"
              memory: "100Mi"
            requests:
              cpu: "0.5"
              memory: "50Mi"
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html 
      initContainers:
        - name: init-app-content
          image: busybox:1.28
          command: ['sh', '-c', 'echo "Hello, from the init container!" > /usr/share/nginx/html/index.html']
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html 
      volumes: 
      - name: data
        persistentVolumeClaim: 
          claimName: database-pvc      
---
kind: Service
apiVersion: v1 
metadata: 
  name: webapp-svc
  namespace: volume-experiment
spec: 
  type: ClusterIP
  ports: 
    - port: 80 
  selector: 
    app: webapp
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volume-experiment-ingress
  namespace: volume-experiment
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cluster.minikube.internal
      http:
        paths:
          - path: /volume-experiment
            pathType: Prefix
            backend:
              service:
                name: webapp-svc
                port:
                  number: 80
